Add option to award solo experience to characters
manuelVo/foundryvtt-award-xp pull request #1
Opened 2021-01-29 21:41 UTC by krysztalzg

Hey, I've fiddled a little with this module and added option to enable awarding solo xp to specific players (like roleplay bonus etc.).

![settings](https://user-images.githubusercontent.com/6009785/106330173-0fc8fc80-6283-11eb-9000-fe7e75f38fa3.png)
![dialog](https://user-images.githubusercontent.com/6009785/106330176-1192c000-6283-11eb-94bd-626aa6a33a1d.png)
![message](https://user-images.githubusercontent.com/6009785/106330180-12c3ed00-6283-11eb-9459-0f8ffe2757b3.png)

2021-01-30 14:03 UTC, manuelVo requested changes
Thanks for your contribution. That's indeed a great idea. Overall it looks pretty good. I think it would be quite nice to have a label above the input boxes for the bonus xp that indicate that these are the boxes for the bonus xp.

Additionally I've added a few comments about things in the code that I'd like to see improved a bit before I merge this.

2021-01-30 14:03 UTC, manuelVo commented on src/main.js
> +		var soloXp = 0;
Please use `let` instead of `var`, since `var` has some weird behavior (it's initialized earlier than usually expected and can be redeclared).

2021-01-30 14:03 UTC, manuelVo commented on src/main.js
> +			soloXpMessages[pc.actor.id] = ' (+' + soloXp + ' bonus xp)';
The parenthesis should be added in the corresponding template `awarded_experience_message.html`. Please localize `bonus xp` as well.

Additionally I think it would be better to only show the bonus xp text if the character actually received bonus xp.

2021-01-30 14:03 UTC, manuelVo commented on src/main.js
> +			var soloXp = Array.from(html.querySelectorAll(".award-xp-solo")).filter(input => input.name == "xp" + pc.actor.id).map(input => parseInt(input.value)).map(value => isNaN(value) ? 0 : value)[0];
Please pull this out of the foreach loop, so we can avoid calling querySelectorAll multiple times.

2021-01-30 14:03 UTC, manuelVo commented on src/settings.js
> +	game.settings.register("award-xp", "character-solo-xp-input", {
I think I'd prefer this setting being below the filter menu button.

2021-01-30 14:03 UTC, manuelVo commented on templates/award_experience_dialog.html
>  	{{/each}}
Wrap the input into a `<div>`. This will cause the input field to be aligned properly in the table.

2021-01-30 14:03 UTC, manuelVo commented on src/style.css
> +.award-xp-solo {
Wrap the input into a `div` (see `award_experience_dialog.html`). That will take care of aligning the input box properly, making this css rule unnecessary.

2021-01-30 14:03 UTC, manuelVo commented on src/util.js
> +	return game.actors.filter(actor => actor.data.type === "character").map(actor =>{return {id: actor.id, name: actor.data.name, image: actor.data.img, showSoloXp: game.settings.get("award-xp", "charac
Please pass the `showSoloXp` settings only once into the template instead of once for every pc.

2021-01-31 16:00 UTC, krysztalzg commented
Thanks for feedback @manuelVo, I'm not sure if it is possible to use `if` in `each` loops for html templates, so I've had to do it this way.

2021-02-01 10:02 UTC, manuelVo requested changes
Thanks for your effort. This looks pretty great now. I'm especially like the idea of just using the placeholder attribute to provide the hint of what to put into those input boxes.

I've added a few last points that I'd like to be addressed and then this should be ready to merge.

2021-02-01 10:02 UTC, manuelVo commented on src/style.css
> +}
This removes the final new line at the end of the file. Please leave it there.

2021-02-01 10:02 UTC, manuelVo commented on templates/award_experience_dialog.html
> +			<div><div><input class="award-xp-char-selector" type="checkbox" name="{{this.id}}" checked/></div><div class="award-xp-char-img-box"><img src="{{this.image}}"/></div><div>{{this.name}}</div><div><
You can access `showSoloXp` from inside the `each` loop by using `{{#if ../showSoloXp}}`.

Also while you're at it, I think the line has reached a length where it would warrant putting each table column into a separate line.

2021-02-01 10:02 UTC, manuelVo commented on src/main.js
> +			soloXpPerCharacter[pc.actor.id] = soloXpInputs.filter(input => input.name == "xp" + pc.actor.id).map(input => parseInt(input.value)).map(value => isNaN(value) ? 0 : value)[0];
This line could be shortened like this (hopefully increasing readability):
```soloXpInputs.find(input => input.name === `xp${pc.actor.id})?.value || 0```

2021-02-02 23:16 UTC, krysztalzg commented
Whew, I wish I wouldn't have to dabble in javascript so much 😂 I've added those last adjustments.

2021-02-03 00:17 UTC, manuelVo approved these changes
This looks good now. Thanks.

2021-02-03 00:21 UTC, merged